version: "3"

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8001:80"
    volumes:
      - ./batch:/php-scratch/batch
      - ./app:/php-scratch/app
    depends_on:
      - db

  db:
    build: ./docker/db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
    ports:
      - 33006:3306
    volumes:
      - "sampledb_data:/var/lib/mysql"
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
    restart: always

volumes:
  sampledb_data:
    driver: local
